$path = 'c:\Users\ASUS\OneDrive\Desktop\Anunayy\AntiGravity\LPU-Nexus\components\AdminStats.tsx';
$content = Get-Content $path;
$content = $content -replace 'font-black text-slate-400 uppercase tracking-\[0.25em\]', 'font-bold text-slate-400 tracking-wide';
$content = $content -replace 'font-black text-slate-400 uppercase tracking-\[0.2em\]', 'font-bold text-slate-400 tracking-wide';
$content = $content -replace 'font-black text-slate-400 uppercase tracking-\[0.3em\]', 'font-bold text-slate-400 tracking-wide';
$content = $content -replace 'text-\[9px\] font-black text-slate-400 uppercase tracking-\[0.25em\]', 'text-[10px] font-bold text-slate-400 tracking-wide';
$content = $content -replace 'text-xs font-black text-slate-900', 'text-xs font-bold text-slate-900';
$content = $content -replace 'text-xs font-black uppercase tracking-tight', 'text-xs font-bold tracking-tight';
$content = $content -replace 'text-\[9px\] font-black uppercase tracking-\[0.15em\]', 'text-[10px] font-bold tracking-tight';
$content = $content -replace 'font-black text-slate-400 uppercase tracking-\[0.4em\]', 'font-bold text-slate-400 tracking-wide';
$content = $content -replace 'Inspect Full View', 'Inspect Full Profile';
$content = $content -replace 'Grid Empty', 'Registry Empty';
$content | Set-Content $path;
